export enum Jass_Type {
    Jass_Boolean = "boolean",
    Jass_Code = "code",
    Jass_Handle = "handle",
    Jass_Integer = "integer",
    Jass_Real  = "real",
    Jass_String = "string",

    Jass_Ability = "ability",
    Jass_Agent = "agent",
    Jass_AiDifficulty= "aidifficulty",
    Jass_AllianceType = "alliancetype",
    Jass_AttackType = "attacktype",
    Jass_BlendMode = "blendmode",
    Jass_BoolExpr = "boolexpr",
    Jass_Buff = "buff",
    Jass_Button = "button",
    Jass_CameraField = "camerafield",
    Jass_CameraSetUp = "camerasetup",
    Jass_ConditionFunc = "conditionfunc",
    Jass_DamageType = "damagetype",
    Jass_DefeatCondition = "defearcondition",
    Jass_Destructable = "destructable",
    Jass_Dialog = "dialog",
    Jass_DialogEvent = "dialogevent",
    Jass_Effect = "effect",
    Jass_Event = "event",
    Jass_EventId = "eventid",
    Jass_FGameState = "fgamestate",
    Jass_FilterFunc = "filterfunc",
    Jass_FogModifier = "fogmodifier",
    Jass_FogState = "fogstate",
    Jass_Force = "force",
    Jass_GameCache = "gamecache",
    Jass_GameDifficulty = "gamedifficulty",
    Jass_GameEvent = "gameevent",
    Jass_GameSpeed = "gamespeed",
    Jass_GameState = "gamestate",
    Jass_GameType = "gametype",
    Jass_Group = "group",
    Jass_HashTable = "hashtable",
    Jass_IGameState = "igamestate",
    Jass_Image = "image",
    Jass_Item = "item",
    Jass_ItemPool = "itempool",
    Jass_LeaderBoard = "leaderboard",
    Jass_Lightning = "lightning",
    Jass_Limitop = "limitop",
    Jass_Location = "location",
    Jass_MapControl = "mapcontrol",
    Jass_MapDensity = "mapdensity",
    Jass_MapFlag = "mapflag",
    Jass_MapSetting = "mapsetting",
    Jass_MapVisibility = "mapvisibility",
    Jass_MultiBoard = "multiboard",
    Jass_MultiBoardItem = "multiboarditem",
    Jass_PathingType = "pathingtype",
    Jass_Placement = "placement",
    Jass_Player = "player",
    Jass_PlayerColor = "playercolor",
    Jass_PlayerGameResult = "playergameresult",
    Jass_PlayerScore = "playerscore",
    Jass_PkayerSlotState = "playersoltstate",
    Jass_PlayerUnitEvent = "playerunitevent",
    Jass_Quest = "quest",
    Jass_QuestItem = "questitem",
    Jass_Race ="race",
    Jass_RacePreference = "recepreference",
    Jass_RarityControl = "raritycontrol",
    Jass_Rect = "rect",
    Jass_Region = "region",
    Jass_Sound = "sound",
    Jass_SoundType = "soundtype",
    Jass_StartLocPrio = "statrlocprio",
    Jass_TerraindeFormation = "terraindeformation",
    Jass_TexMapFlags = "texmapflags",
    Jass_TextTag = "texttag",
    Jass_Timer = "timer",
    Jass_TimerDialog = "timerdialog",
    Jass_Trackable = "trackable",
    Jass_Trigger = "trigger",
    Jass_TriggerAction = "triggeraction",
    Jass_UberSplat = "ubersplat",
    Jass_Unit = "unit",
    Jass_UnitEvent = "unitevent",
    Jass_UnitPool = "unitPool",
    Jass_UnitState = "unitstate",
    Jass_UnitType = "unittype",
    Jass_Version = "version",
    Jass_VolumeGroup = "volumegroup",
    Jass_WeaponType = "weapontype",
    Jass_WeatherEffect = "weathereffect",
    Jass_Widget = "widget",
    Jass_WidgetEVent = "widgetevent"
}










